### ISSUE TITLE
option to disable thumbnail cache?

### ISSUE THREAD

**Issue by andresmrm** [karlch/vimiv#14]
Thanks for vimiv! Seems pretty good so far!

Is there an option to disable thumbnail cache?

**Comment by karlch** [comment]
Glad you like it.

No, not yet. I guess this wouldn't be difficult to implement, so I will add this to my TODO list. I am afraid I'm really busy currently, so this could take a while.

**Comment by andresmrm** [comment]
Thanks! Just tested and it seems to work!

**Comment by karlch** [comment]
Nice :smiley:

There are still some hickups in the new version but I hope to get it all stable until the end of the week.

**Comment by woefe** [comment]
Hi @andresmrm,
I am currently working on issue #37, which implements the freedesktop.org thumbnail management standard. The idea of this standard is that applications use a shared thumbnail cache. When #37 is fixed, disabling the cache in vimiv does not make sense anymore, because other applications will eventually generate the thumbnails for vimiv. Disabling the cache would also lead to a lot of computational overhead, especially when using vimiv on large files and directories. When my pull request is accepted, the requested feature of this issue will unfortunately be removed.

**Comment by andresmrm** [comment]
Hi, @woefe !
It's ok, I'll survive. ;)
My reason to disable cache was to avoid SSD writes. But now I also bought an HDD, so I'm fine.
And thanks for taking your time to tell me about that!
