### ISSUE TITLE
Display metadata

### ISSUE THREAD

**Issue by tjaartvdwalt** [karlch/vimiv#64]
First off, thanks for a great image viewer!

It would be really great if it was possible to view image metadata with `vimiv`.
Mainly I am interested in JPEG exif data, but it may be useful for other image types as well.

Below is an example of how `feh` supports this concept. 

~~~shell
feh --draw-exif my_image.jpg
~~~

![2018-03-05-152926_4480x1080_scrot](https://user-images.githubusercontent.com/2066766/37005775-298ec002-208a-11e8-8906-e2ea8db6c091.png)

**Comment by karlch** [comment]
Thanks!

Sounds like a nice feature, I will think about how to implement this neatly. But once again I will defer this until #61 is completed which may take a while.

**Comment by karlch** [comment]
Closing as this has already been implemented in the [Qt port](https://github.com/karlch/vimiv-qt) and no new features will be implemented here.
I hope the new version can be of some use to you, in case anything is missing [please open an issue](https://github.com/karlch/vimiv-qt/issues).
The current display of metadata is not very detailed though, mainly because I am not very experienced with exif and don't know what information is useful to camera-lovers and how it should be formatted. Therefore there is [this follow-up issue](https://github.com/karlch/vimiv-qt/issues/100).
