### ISSUE TITLE
Keybinding to open an image

### ISSUE THREAD

**Issue by petobens** [karlch/vimiv#71]
I know I can open images my pressing `Return`. I want to map `o` (open) to achieve the same behaviour.
I tried with `o: Return` in my `keys.conf` file but I (obviously) doesn't work. Is there a workaround for this? Thanks

**Comment by karlch** [comment]
Meaning you would like `o` in the library to behave like `Return`? It is simple for it to behave like `l`, the binding would then be `o: scroll_lib l`, but actually also closing the library is currently not possible.

**Comment by petobens** [comment]
Ok. Thanks! Will use `o: scroll_lib l` then.

**Comment by petobens** [comment]
I there a similar trick for thumbnail mode?

**Comment by karlch** [comment]
Unfortunately not, I actually think this is a more general problem. The `Return` key is used, as it emits a signal in Gtk. There are other keys, which have internal functionality and aren't implemented using the standard command interface. I think this could be solved in general by adding functionality similar to vim's `:map` command, not sure where this would go in the config though.

**Comment by petobens** [comment]
That's a good idea!

**Comment by karlch** [comment]
The initial issue has been fixed in the [Qt port](https://github.com/karlch/vimiv-qt) with the `:open-selected` command within [this issue](https://github.com/karlch/vimiv-qt/issues/34) for both library and thumbnail mode. I have not found a different usecase for the `:map` command yet, although it would not be too difficult to implement. Feel free to [open an issue](https://github.com/karlch/vimiv-qt/issues) there if you can think of more general usecases for the `:map` command. Sorry for the version chaos, I'm trying to clean up :smile:
