### ISSUE TITLE
Can't open image with xdg-open

### ISSUE THREAD

**Issue by petobens** [karlch/vimiv#72]
Running `xdg-mime query default image/png` correctly reports `vimiv.desktop` but when I run `xdg-open foo.png` instead of opening the image the library is opened. This might be related to #70.

**Comment by karlch** [comment]
I can reproduce this, what happens is that due to the `--start-from-desktop` flag the working directory is changed to the `desktop_start_dir` setting and the relative path given in the command line is no longer correct. It therefore doesn't find the image and falls back to opening the library, as it has no more images to show.

This can be solved by:
* Removing the `--start-from-desktop` from the `vimiv.desktop` file
* Setting `desktop_start_dir` to `.` in the vimivrc

**Comment by petobens** [comment]
Awesome. Thank you!
