### ISSUE TITLE
Display bar appears on vimiv open

### ISSUE THREAD

**Issue by leoperegrino** [karlch/vimiv#83]
## Issue
Even though I have set **display_bar** to **no**, everytime i open an image, it opens with the bar but without any info. I don't know if this is a bug or intentionally built. 

## Workarround
I have to press b 2 times so I can see the picture without any bar.

## Question
Is there a way to open without **any** bar?

**Comment by karlch** [comment]
Thanks for the nice bug report! I was able to reproduce this and can confirm that this is a bug, not an intention.

Would it be feasible for you to switch to the [qt port](https://github.com/karlch/vimiv-qt)? Here this issue is not present and there are many other improvements. This would be done by setting the `show` setting in the `STATUSBAR` section to false.

It is quite difficult for me to come back to this codebase, as all my focus is on the new one. If it is not feasible for you to switch, I would take some time maybe on the week-end. But note that at some point the qt version will become the default and this will be essentially unsupported.

**Comment by leoperegrino** [comment]
First of all, I would like to thank you for your dedication to this project which I found amazing: simple and efficient.

I was not aware of another version with qt, just downloaded directly from pacman in arch linux. I'm going to try and give you a feedback but no need for taking extra time.

**Comment by karlch** [comment]
Thanks for these warm words. You should be able to get the [latest qt version](https://aur.archlinux.org/packages/vimiv-qt/) and the [latest development version via git](https://aur.archlinux.org/packages/vimiv-qt-git/) from the AUR.

Sorry for the current version chaos. The plan is to replace the gtk version also in the arch repositories with the release of version `1.0` which is expected hopefully somewhen in summer this year. I just felt that a re-write was absolutely necessary in case I want to further improve vimiv. If you like, you can read some more information [in the corresponding issue](https://github.com/karlch/vimiv/issues/61).

**Comment by leoperegrino** [comment]
I've downloaded the qt version from git and finished the configuration. Everything is as expected, no blank bar when oppening. The already built-in dark theme is very pleasant.

Keep up the good work! This is going to be my default image viewer.
